default:
  tags:
    - mace-micro
  image: mace-micro-dev

before_script:
  - git submodule deinit -f .
  - git submodule sync
  - git submodule update --init .

stages:
  - convert
  - build
  - test

model-convert:
  stage: convert
  script:
    - bash micro/tools/ci/model_convert.sh
  artifacts:
    paths:
      - mace-models
    untracked: true

cross-build:
  stage: build
  script:
    - bash micro/tools/ci/cross_build.sh
    - bash micro/tools/ci/host_build_and_run_examples.sh
    - bash micro/tools/ci/host_build_and_run_tests.sh
    - bash micro/tools/ci/build_mbed_example.sh

