stages:
  - linting
  - basic-build
  - smoke-test
  - build
  - test
  - extra

cpplint:
  stage: linting
  script:
    - sh tools/cpplint.sh

pylint:
  stage: linting
  script:
    - pycodestyle $(find -name "*.py")

build_docs:
  stage: basic-build
  script:
    - cd docs
    - make html
    - CI_LATEST_OUTPUT_PATH=/mace-build-output/$CI_PROJECT_NAME/latest
    - CI_JOB_OUTPUT_PATH=/mace-build-output/$CI_PROJECT_NAME/$CI_PIPELINE_ID
    - rm -rf $CI_JOB_OUTPUT_PATH
    - mkdir -p $CI_JOB_OUTPUT_PATH
    - cp -r _build/html $CI_JOB_OUTPUT_PATH/docs
    - rm -rf $CI_LATEST_OUTPUT_PATH
    - mkdir -p $CI_LATEST_OUTPUT_PATH
    - cp -r _build/html $CI_LATEST_OUTPUT_PATH/docs

  artifacts:
    paths:
      - docs/_build

build_android-armeabi-v7a:
  stage: basic-build
  script:
    - sh tools/build-android-armeabi-v7a-full.sh

build_android-arm64-v8:
  stage: basic-build
  script:
    - sh tools/build-android-arm64-v8a-full.sh

code_footprint_check:
  stage: basic-build
  script:
    - echo check shared library size

cc_test_smoketest:
  stage: smoke-test
  script:
    - echo tests

cc_benchmark_smoketest:
  stage: smoke-test
  script:
    - echo benchmark

build_arm-linux-gnueabihf:
  stage: build
  script:
    - sh tools/build-arm-linux-gnueabihf-full.sh
  only:
    - triggers

build_aarch64-linux-gnu:
  stage: build
  script:
    - sh tools/build-aarch64-linux-gnu-full.sh
  only:
    - triggers

build_host:
  stage: build
  script:
    - sh tools/build-host.sh
  only:
    - triggers

build_android_demo:
  stage: build
  script:
    - echo build android demo
  only:
    - triggers

cc_test:
  stage: test
  script:
    - echo cc_test
  only:
    - triggers

cc_benchmark:
  stage: test
  script:
    - echo cc_benchmark
  only:
    - triggers

quantization_test:
  stage: test
  script:
    - echo quantization_test
  only:
    - triggers

model_test:
  stage: test
  script:
    - echo model_test
  only:
    - triggers

ndk_compatibility_check:
  stage: extra
  script:
    - echo ndk_compatibility_check
  only:
    - triggers

python_compatibility_check:
  stage: extra
  script:
    - echo python3 check
  only:
    - triggers

extra_tests:
  stage: extra
  script:
    - ops_test_disable_neon
    - ops_test
    - api_test
    - extra_tests
    - dynamic_link_test
  only:
    - triggers
